server:
  port: 3002
  tomcat:
    max-connections: 1000
    max-threads: 500
eureka:
  instance:
    appname: monitor-server
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:3003/eureka/
